//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Ohm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="Ohm.IOpenHomeMationServer")]
    public interface IOpenHomeMationServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IOpenHomeMationServer/Query", ReplyAction="http://Microsoft.ServiceModel.Samples/IOpenHomeMationServer/QueryResponse")]
        string Query([System.ServiceModel.MessageParameterAttribute(Name="query")] string query1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IOpenHomeMationServer/Query", ReplyAction="http://Microsoft.ServiceModel.Samples/IOpenHomeMationServer/QueryResponse")]
        System.Threading.Tasks.Task<string> QueryAsync(string query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOpenHomeMationServerChannel : global::WebApplication1.Ohm.IOpenHomeMationServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OpenHomeMationServerClient : System.ServiceModel.ClientBase<global::WebApplication1.Ohm.IOpenHomeMationServer>, global::WebApplication1.Ohm.IOpenHomeMationServer {
        
        public OpenHomeMationServerClient() {
        }
        
        public OpenHomeMationServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OpenHomeMationServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenHomeMationServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenHomeMationServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Query(string query1) {
            return base.Channel.Query(query1);
        }
        
        public System.Threading.Tasks.Task<string> QueryAsync(string query) {
            return base.Channel.QueryAsync(query);
        }
    }
}
